app/modules/admin/controllers/ReplyToMessageController.php
<?php

namespace app\modules\admin\controllers;

use app\models\UserMessage;
use Yii;
use app\models\ReplyToMessage;
use app\models\ReplyToMessageSearch;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ReplyToMessageController implements the CRUD actions for ReplyToMessage model.
 */
class ReplyToMessageController extends CustomController
{

    /**
     * Lists all ReplyToMessage models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ReplyToMessageSearch();
        $sort = ['id' => SORT_DESC];
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $sort);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ReplyToMessage model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ReplyToMessage model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $messageModel = UserMessage::find()->where(['id' => $id])->one();
        $model = new ReplyToMessage();

        if ($model->load(Yii::$app->request->post())) {

            $model->user_message_id = $messageModel->id;
            $model->create_at       = time();
            if($model->save())
            {
                $messageMail = Yii::$app->mailer->compose();
                $messageMail->setFrom('ss@gmail.com');
                $messageMail->setTo($messageModel->email)
                            ->setSubject('test')
                            ->setTextBody('test')
                            ->send();
                Yii::$app->session->setFlash('alert', ['success', 'ایمیل با موفقیت ارسال شد.']);
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
                'messageModel' => $messageModel,
            ]);
        }
    }

    /**
     * Updates an existing ReplyToMessage model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing ReplyToMessage model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ReplyToMessage model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return ReplyToMessage the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ReplyToMessage::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

app/modules/admin/controllers/UserMessageController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\UserMessage;
use app\models\UserMessageSearch;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserMessageController implements the CRUD actions for UserMessage model.
 */
class UserMessageController extends CustomController
{
    /**
     * Lists all UserMessage models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserMessageSearch();

        $sort = ['id' => SORT_DESC];
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $sort);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single UserMessage model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new UserMessage model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new UserMessage();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing UserMessage model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing UserMessage model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the UserMessage model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return UserMessage the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = UserMessage::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

app/modules/admin/views/reply-to-message/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ReplyToMessage */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
    </div>

    <div class="box-body">

        <div class="reply-to-message-form">

            <?php $form = ActiveForm::begin(); ?>

            <div class="form-group">
                <lable></lable>
                <input type="text" class="form-control" value="<?= Html::encode($messageModel->email)?>" disabled>
            </div>

            <?= $form->field($model, 'reply')->textarea(['rows' => 6]) ?>

            <div class="form-group">
                <?= Html::submitButton($model->isNewRecord ? 'افزودن' : 'ویرایش', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

app/modules/admin/views/reply-to-message/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ReplyToMessageSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="reply-to-message-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_message_id') ?>

    <?= $form->field($model, 'reply') ?>

    <?= $form->field($model, 'create_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

app/modules/admin/views/reply-to-message/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\ReplyToMessage */

$this->title = 'پاسخ به پیام کاربران';
$this->params['breadcrumbs'][] = ['label' => 'پاسخ به پیام کاربران', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="reply-to-message-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'messageModel' => $messageModel
    ]) ?>

</div>

app/modules/admin/views/reply-to-message/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\ReplyToMessageSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'پاسخ های ارسال شده با ایمیل';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
    </div>

    <div class="box-body">

        <div class="reply-to-message-index">

            <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

            <?php Pjax::begin(); ?>    <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'filterModel' => $searchModel,
                    'columns' => [
                        //['class' => 'yii\grid\SerialColumn'],

                        'id',
                        //'user_message_id',
                        [
                            'attribute' => 'user_message_id',
                            'format' => 'raw',
                            'content' => function($data){
                                return Html::a($data->userMessage->email, ['user-message/view', 'id' => $data->user_message_id]);
                            }
                        ],
                        'reply:ntext',
                        //'create_at',
                        /*[
                            'attribute' => 'create_at',
                            'format' => 'raw',
                            'content' => function($data){
                                return \app\components\General::persianDate($data->create_at);
                            }
                        ],*/
                        [
                            'class' => 'yii\grid\ActionColumn',
                            'template' => '{view} {delete}'
                        ],
                    ],
                ]); ?>
            <?php Pjax::end(); ?>
        </div>
    </div>
</div>

app/modules/admin/views/reply-to-message/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ReplyToMessage */

$this->title = 'Update Reply To Message: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Reply To Messages', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="reply-to-message-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

app/modules/admin/views/reply-to-message/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\ReplyToMessage */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'پاسخ به پیام کاربران', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
    </div>

    <div class="box-body">
        <div class="reply-to-message-view">

            <p>
               <!-- <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>-->
                <?= Html::a('حذف', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ]) ?>
            </p>

            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'id',
                    //'user_message_id',
                    [
                        'attribute' => 'user_message_id',
                        'format' => 'html',
                        'value' =>
                            Html::a($model->userMessage->email, ['user-message/view', 'id' => $model->user_message_id]),
                    ],
                    [
                        'attribute' => 'null',
                        'label'  => 'پیام',
                        'format' => 'raw',
                        'value' => $model->userMessage->message,
                    ],
                    'reply:ntext',
                    //'create_at',
                    [
                        'attribute' => 'create_at',
                        'format' => 'raw',
                        'value' => \app\components\General::persianDate($model->create_at),
                    ]
                ],
            ]) ?>

        </div>
    </div>
</div>